language: csharp  
sudo: required  
dist: trusty  
env:  
  - CLI_VERSION=latest
addons:  
  apt:
    packages:
    - curl
    - libunwind8
    - gettext
os:  
  - linux
branches:  
  only:
    - master
install:  
  - curl -sSL -o dotnet.tar.gz https://go.microsoft.com/fwlink/?LinkID=835021
  - sudo mkdir -p /opt/dotnet && sudo tar zxf dotnet.tar.gz -C /opt/dotnet
  - sudo ln -s /opt/dotnet/dotnet /usr/local/bin
script:  
  - cd test/ && dotnet test
